#id: DOq069
#description: >-
# Count of mappings in the DO by predicate (active diseases only), with TOTAL
# and TOTAL (unique) counts
#input: doid.owl
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT ?group ?count
WHERE {
  {
    SELECT ?group (COUNT(?mapping) as ?count)
    WHERE {
      VALUES ?predicate {
        oboInOwl:hasDbXref
        skos:exactMatch
        skos:closeMatch
        skos:broadMatch
        skos:narrowMatch
        skos:relatedMatch
      }

      ?iri ?predicate ?mapping .

      FILTER(CONTAINS(str(?iri), "DOID_"))
      FILTER NOT EXISTS { ?iri owl:deprecated true }
      BIND(
        REPLACE(
          REPLACE(str(?predicate), str(skos:), "skos:"),
          str(oboInOwl:),
          "oboInOwl:"
        ) AS ?group
      )
    }
    GROUP BY ?group
    ORDER BY ?group
  }
  UNION
  {
    SELECT ?group (COUNT(?mapping) as ?count)
    WHERE {
      VALUES ?predicate {
        oboInOwl:hasDbXref
        skos:exactMatch
        skos:closeMatch
        skos:broadMatch
        skos:narrowMatch
        skos:relatedMatch
      }

      ?iri ?predicate ?mapping .

      FILTER(CONTAINS(str(?iri), "DOID_"))
      FILTER NOT EXISTS { ?iri owl:deprecated true }
      BIND("TOTAL" AS ?group)
      BIND(CONCAT(str(?iri), str(?mapping)) AS ?iriMapping)
    }
    GROUP BY ?group
  }
  UNION
  {
    SELECT ?group (COUNT(DISTINCT ?iriMapping) AS ?count)
    WHERE {
      VALUES ?predicate {
        oboInOwl:hasDbXref
        skos:exactMatch
        skos:closeMatch
        skos:broadMatch
        skos:narrowMatch
        skos:relatedMatch
      }

      ?iri ?predicate ?mapping .

      FILTER(CONTAINS(str(?iri), "DOID_"))
      FILTER NOT EXISTS { ?iri owl:deprecated true }
      BIND("TOTAL (unique)" AS ?group)
      BIND(CONCAT(str(?iri), str(?mapping)) AS ?iriMapping)
    }
    GROUP BY ?group
  }
}
